version: '3.9'

services:
  whisper:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisper-priority-image
    container_name: whisper-python-worker
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ./models:/root/.cache/whisper
      - /transcripts:/transcripts
      - /raw:/raw
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - type: bind
        source: ./supervisor-logs
        target: /app/logs
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
    command: sh -c "rm -rf /app/*.log && supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"

