version: '3.9'

networks:
  whisper-net:               # external = already exists
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: whisper-rabbit
    networks:
      - whisper-net
  whisper:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisper-worker-image
    container_name: whisper-python-worker
    networks:
      - whisper-net          # ‚Üê attach!
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      RESULT_QUEUE: ${RESULT_QUEUE}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ./models:/root/.cache/whisper
      - /transcripts:/transcripts
      - /raw:/raw
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - type: bind
        source: ./supervisor-logs
        target: /app/logs
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always
    command: sh -c "rm -rf /app/*.log && supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"

